[phases.setup]
nixPkgs = ['pnpm']

[phases.install]
cmds = ['pnpm install']

[phases.build]
cmds = ['pnpm --filter bookmarket-server run build']

[start]
cmd = 'pnpm --filter bookmarket-server run start:prod'