[phases.setup]
nixPkgs = ['nodejs', 'pnpm']
aptPkgs = ['build-essential']

[phases.install]
cmds = ['pnpm install']
dependsOn = ['setup']

[phases.build]
cmds = ['pnpm --filter bookmarket-server run build']
dependsOn = ['install']

[start]
cmd = 'pnpm --filter bookmarket-server run start:prod'